version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
  nginx:
    image: nginx
    ports:
      - 8443:443
      - 35601:5601
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx-test.conf
      - ./nginx/ssl:/opt/ssl
      - ./nginx/htpasswd:/etc/nginx/.htpasswd
